# Generated by Django 3.0.2 on 2020-02-22 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='timeslots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.IntegerField()),
                ('endtime', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='available',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=30)),
                ('day', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('room_type', models.CharField(choices=[('Suite', 'Suite'), ('Deluxe', 'Deluxe'), ('Standard', 'Standard')], default='Suite', max_length=10)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.person')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.timeslots')),
            ],
        ),
    ]
