# Generated by Django 3.0.2 on 2020-01-30 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='person',
        ),
    ]
