# Generated by Django 3.0.2 on 2020-02-06 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20200206_1109'),
        ('bookings', '0002_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateField()),
                ('room_type', models.CharField(choices=[('Suite', 'Suite'), ('Deluxe', 'Deluxe'), ('Standard', 'Standard')], default='Suite', max_length=8)),
                ('price', models.IntegerField()),
                ('checkout', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='accounts.person')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='accounts.person')),
            ],
        ),
    ]
