# Generated by Django 3.0.2 on 2020-02-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20200223_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='available',
            name='time',
        ),
        migrations.AddField(
            model_name='available',
            name='endtime',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='available',
            name='starttime',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
