# Generated by Django 3.0.2 on 2020-02-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_auto_20200223_0103'),
    ]

    operations = [
        migrations.CreateModel(
            name='number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=30)),
            ],
        ),
    ]
