# Generated by Django 3.0.2 on 2020-02-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='number',
            name='day_adv',
            field=models.IntegerField(default=5),
        ),
    ]
