# Generated by Django 3.0.2 on 2020-02-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_number_day_adv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='available',
            name='room_type',
            field=models.CharField(choices=[('Suite', 'Suite'), ('Deluxe', 'Deluxe')], default='Suite', max_length=10),
        ),
    ]
