# Generated by Django 3.0.2 on 2020-02-09 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_auto_20200209_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='room',
            name='start_time',
        ),
    ]
