# Generated by Django 3.0.2 on 2020-03-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_auto_20200227_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='booked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('room_t', models.CharField(max_length=8)),
                ('startime', models.IntegerField()),
                ('endtime', models.IntegerField()),
                ('customer', models.CharField(max_length=20)),
            ],
        ),
    ]
