# Generated by Django 3.0.2 on 2020-02-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_auto_20200209_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='availableno',
        ),
        migrations.RemoveField(
            model_name='room',
            name='booked',
        ),
        migrations.AddField(
            model_name='room',
            name='checkout',
            field=models.DateField(default=8),
            preserve_default=False,
        ),
    ]
