# Generated by Django 3.0.2 on 2020-03-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_booked_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='day_adv',
            field=models.IntegerField(default=3),
        ),
    ]
