# Generated by Django 3.0.2 on 2020-03-15 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_auto_20200312_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='day_adv',
            field=models.IntegerField(default=2),
        ),
    ]
