# Generated by Django 3.0.2 on 2020-02-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='days_adv',
            field=models.IntegerField(default=30),
        ),
    ]
