# Generated by Django 3.0.2 on 2020-02-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default='M', max_length=8),
        ),
        migrations.AlterField(
            model_name='person',
            name='user_type',
            field=models.CharField(choices=[('Room Manager', 'Room Manager'), ('Customer', 'Customer')], default='Customer', max_length=20),
        ),
    ]
