# Generated by Django 3.0.2 on 2020-02-25 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_person_days_adv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='days_adv',
        ),
    ]
