# Generated by Django 3.0.2 on 2020-02-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200206_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.IntegerField(),
        ),
    ]
