# Generated by Django 3.0.2 on 2020-02-09 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200209_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='dob',
            field=models.DateField(default=datetime.date(1970, 1, 1)),
        ),
    ]
